# Generated by Django 6.0.6 on 2026-07-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du véhicule')),
                ('brand', models.CharField(max_length=50, verbose_name='Marque')),
                ('category', models.CharField(choices=[('economique', 'Économique'), ('confort', 'Confort'), ('premium', 'Premium'), ('suv', 'SUV')], default='economique', max_length=20, verbose_name='Catégorie')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix par jour (MAD)')),
                ('seats', models.PositiveIntegerField(default=5, verbose_name='Nombre de places')),
                ('transmission', models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], default='manuelle', max_length=20, verbose_name='Transmission')),
                ('fuel_type', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('hybride', 'Hybride')], default='diesel', max_length=20, verbose_name='Carburant')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('image_url', models.URLField(blank=True, verbose_name="URL de l'image")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voiture',
                'verbose_name_plural': 'Voitures',
                'ordering': ['price_per_day'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
