# Generated by Django 6.0.6 on 2026-07-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('rating', models.PositiveIntegerField(default=5, help_text='Note de 1 à 5 étoiles', verbose_name='Note')),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Avis client',
                'verbose_name_plural': 'Avis clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='featured',
            field=models.BooleanField(default=False, verbose_name="Affiché en page d'accueil"),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Photo du véhicule'),
        ),
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.URLField(blank=True, verbose_name="URL de l'image (ancien)"),
        ),
    ]
