# Generated by Django 6.0.6 on 2026-07-30 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_review_car_featured_car_image_alter_car_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la marque')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Logo')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name="Pays d'origine")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('cin', models.CharField(max_length=20, unique=True, verbose_name='CIN')),
                ('drivers_license', models.CharField(blank=True, max_length=50, verbose_name='Permis de conduire')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('cin_front', models.ImageField(blank=True, null=True, upload_to='clients/cin/', verbose_name='CIN Recto')),
                ('cin_back', models.ImageField(blank=True, null=True, upload_to='clients/cin/', verbose_name='CIN Verso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='car',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, verbose_name='Immatriculation'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilométrage'),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=50, verbose_name='Marque (texte)'),
        ),
        migrations.AddField(
            model_name='car',
            name='brand_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='core.brand', verbose_name='Marque'),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name="Compagnie d'assurance")),
                ('insurance_type', models.CharField(choices=[('tous_risques', 'Tous risques'), ('tiers', 'Tiers'), ('tiers_plus', 'Tiers+'), ('autre', 'Autre')], default='tous_risques', max_length=20, verbose_name='Type')),
                ('policy_number', models.CharField(blank=True, max_length=50, verbose_name='N° de police')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('expiry_date', models.DateField(verbose_name="Date d'expiration")),
                ('annual_premium', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prime annuelle (MAD)')),
                ('document', models.FileField(blank=True, null=True, upload_to='insurances/', verbose_name='Document scanné')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='core.car', verbose_name='Voiture')),
            ],
            options={
                'verbose_name': 'Assurance',
                'verbose_name_plural': 'Assurances',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='N° de contrat')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix par jour (MAD)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total (MAD)')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Caution (MAD)')),
                ('km_start', models.PositiveIntegerField(default=0, verbose_name='Km au départ')),
                ('km_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='Km au retour')),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.car', verbose_name='Voiture')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Contrat de location',
                'verbose_name_plural': 'Contrats de location',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='Date de la visite')),
                ('expiry_date', models.DateField(verbose_name="Date d'expiration")),
                ('result', models.CharField(choices=[('favorable', 'Favorable'), ('defavorable', 'Défavorable')], default='favorable', max_length=20, verbose_name='Résultat')),
                ('center_name', models.CharField(blank=True, max_length=200, verbose_name='Centre de contrôle')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Coût (MAD)')),
                ('document', models.FileField(blank=True, null=True, upload_to='inspections/', verbose_name='Document scanné')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='core.car', verbose_name='Voiture')),
            ],
            options={
                'verbose_name': 'Visite technique',
                'verbose_name_plural': 'Visites techniques',
                'ordering': ['-expiry_date'],
            },
        ),
    ]
