# Generated by Django 6.0.6 on 2026-07-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_brand_client_car_color_car_license_plate_car_mileage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='URL du Logo'),
        ),
    ]
