# Generated by Django 6.0.6 on 2026-07-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_brand_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de retour prévue'),
        ),
    ]
