# Generated by Django 6.0.6 on 2026-07-31 19:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_car_expected_return_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SAOUD CAR', max_length=100, verbose_name='Raison Sociale')),
                ('email', models.EmailField(default='saoud88000@gmail.com', max_length=254, verbose_name='Email')),
                ('phone_mobile', models.CharField(default='+212661395495', max_length=20, verbose_name='Téléphone mobile')),
                ('phone_fixed', models.CharField(default='+212523290058', max_length=20, verbose_name='Téléphone fixe')),
                ('address', models.TextField(default='Citee Lalla Meriem Bloc B N 185', verbose_name='Adresse')),
                ('city', models.CharField(default='BENSLIMANE', max_length=50, verbose_name='Ville')),
                ('zip_code', models.CharField(default='13000', max_length=20, verbose_name='Code postal')),
                ('country', models.CharField(default='Maroc', max_length=50, verbose_name='Pays')),
                ('website', models.CharField(blank=True, max_length=100, verbose_name='Site Web')),
                ('ice', models.CharField(default='000058659000023', max_length=50, verbose_name='ICE')),
                ('patente', models.CharField(default='39715439', max_length=50, verbose_name='Patente')),
                ('rc', models.CharField(default='2713', max_length=50, verbose_name='RC')),
                ('if_tax', models.CharField(default='40 39 14 74', max_length=50, verbose_name='IF')),
                ('cnss', models.CharField(default='8744080', max_length=50, verbose_name='CNSS')),
                ('tva', models.PositiveIntegerField(default=20, verbose_name='TVA (%)')),
            ],
            options={
                'verbose_name': "Informations de l'agence",
                'verbose_name_plural': "Informations de l'agence",
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('current_mileage', models.PositiveIntegerField(verbose_name='Kilométrage actuel')),
                ('next_mileage', models.PositiveIntegerField(verbose_name='Prochaine vidange (Km)')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Coût (MAD)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='core.car', verbose_name='Voiture')),
            ],
            options={
                'verbose_name': 'Vidange / Entretien',
                'verbose_name_plural': 'Vidanges / Entretiens',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.car', verbose_name='Voiture')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='core.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
