# Generated by Django 6.0.6 on 2026-08-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agencyinfo_maintenance_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyinfo',
            name='conditions_generales',
            field=models.TextField(default='Article 1 – État du véhicule\nLe véhicule est remis au locataire en parfait état de marche.\nLe locataire doit vérifier immédiatement l’état du véhicule ainsi que les accessoires fournis (roue de secours, outils, etc.).\nLe véhicule doit être restitué dans le même état que celui constaté lors de la remise.\n\nLe locataire doit :\nNe faire aucune modification au véhicule.\nRetourner le véhicule propre.\nRespecter la limite de 200 km par jour, sauf accord contraire.\nS’assurer que le compteur reste lisible et intact.\nTout dommage non signalé lors du retour sera à la charge du locataire.\n\nArticle 2 – Utilisation du véhicule\nLa location est personnelle et non transmissible.\nLe locataire s’engage à :\nUtiliser le véhicule uniquement pour ses besoins personnels.\nRespecter le code de la route.\nNe permettre la conduite qu’aux conducteurs autorisés et mentionnés au contrat.\nIl est strictement interdit de :\nTransporter des marchandises contre rémunération.\nUtiliser le véhicule pour des courses, rallyes ou compétitions.\nTransporter des objets dangereux.\nUtiliser le véhicule pour pousser un autre véhicule.\nFaire du remorquage.\nToute utilisation contraire engage la responsabilité totale du locataire.\n\nArticle 3 – Carburant et lubrifiants\nLe carburant est entièrement à la charge du locataire.\nLe locataire doit contrôler régulièrement :\nLes niveaux d’huile\nLe liquide de frein\nLe liquide de refroidissement\nLes frais de graissage et d’entretien courant sont à la charge du locataire.\nIl devra fournir des factures justifiant les opérations effectuées (avec indication du kilométrage).\n\nArticle 4 – Entretien et réparations\nLes réparations dues à l’usure normale sont à la charge du loueur.\nLes réparations dues à une mauvaise utilisation, un accident ou une négligence sont à la charge du locataire.\nLe locataire ne peut effectuer aucune réparation sans autorisation préalable du loueur, sauf en cas d’urgence.\nToute immobilisation du véhicule causée par une mauvaise utilisation entraîne une indemnité.\n\nArticle 5 – Assurance et accident\nL’assurance couvre :\nLes dommages causés au véhicule conformément au contrat.\nLa responsabilité civile obligatoire.\nLe locataire reste responsable :\nDes dommages résultant d’une mauvaise utilisation.\nDes vols causés par négligence (véhicule non fermé, clés laissées à l’intérieur).\nDes objets personnels transportés.\nEn cas d’accident :\nLe locataire doit informer immédiatement la société.\nRemplir un constat amiable.\nFournir les coordonnées des témoins éventuels.\n\nArticle 6 – Règlement – Prépaiement – Prolongation\nLe prépaiement sert uniquement à réserver la location.\nToute prolongation doit être validée et réglée auprès de la société.\nLes frais supplémentaires (carburant, retards, dommages, jours ajoutés) sont à la charge du locataire.\nLa société se réserve le droit de récupérer le véhicule à tout moment en cas de non-respect du contrat.\n\nArticle 7 – Documents du véhicule\nLe locataire doit restituer :\nLa carte grise\nL’assurance\nLes clés\nLes documents du véhicule\nEn cas de perte, les frais de duplicata seront à la charge du locataire.\n\nArticle 8 – Responsabilité\nLe locataire est responsable :\nDe toute amende ou infraction commise durant la location.\nDes dommages causés au véhicule non couverts par l’assurance.\nDe la perte d’objets ou d’accessoires fournis.\n\nArticle 9 – Juridiction\nEn cas de litige, les tribunaux compétents seront ceux du lieu de signature du contrat.', verbose_name='Conditions Générales'),
        ),
        migrations.AddField(
            model_name='agencyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='agency/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='agencyinfo',
            name='show_stamp_on_contract',
            field=models.BooleanField(default=True, verbose_name='Afficher Sur le Contrat'),
        ),
        migrations.AddField(
            model_name='agencyinfo',
            name='show_stamp_on_invoice',
            field=models.BooleanField(default=True, verbose_name='Afficher Sur la Facture'),
        ),
        migrations.AddField(
            model_name='agencyinfo',
            name='stamp',
            field=models.ImageField(blank=True, null=True, upload_to='agency/', verbose_name='Cachet'),
        ),
    ]
