# Generated by Django 6.0.6 on 2026-08-01 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agencyinfo_conditions_generales_agencyinfo_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='client',
            name='cin_expiry',
            field=models.DateField(blank=True, null=True, verbose_name="Valable jusqu'au (CIN)"),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, default='Maroc', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=10, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='client',
            name='license_delivered',
            field=models.DateField(blank=True, null=True, verbose_name='Délivré le'),
        ),
        migrations.AddField(
            model_name='client',
            name='nationality',
            field=models.CharField(blank=True, default='Marocaine', max_length=100, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_expiry',
            field=models.DateField(blank=True, null=True, verbose_name="Valable jusqu'au (Passeport)"),
        ),
        migrations.AddField(
            model_name='client',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° Passeport'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='client_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature client'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='client_signed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date signature client'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='director_signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature directeur'),
        ),
        migrations.AddField(
            model_name='rentalcontract',
            name='signature_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token de signature'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cin',
            field=models.CharField(max_length=20, unique=True, verbose_name='N° CIN'),
        ),
        migrations.AlterField(
            model_name='client',
            name='drivers_license',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° Permis'),
        ),
    ]
